version: 2
updates:
  - package-ecosystem: npm
    directory: /node
    target-branch: develop
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@mui/material"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@mui/icons-material"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@mui/x-data-grid"
        update-types: ["version-update:semver-major"]
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: uv
    directory: /flaskapi
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"
