version: "3.7"
services:
  mmux-vite-backend:
    image: simcore/services/dynamic/mmux-vite-backend:1.0.0
    environment:
      - OSPARC_API_BASE_URL=${OSPARC_API_BASE_URL}
      - OSPARC_API_KEY=${OSPARC_API_KEY}
      - OSPARC_API_SECRET=${OSPARC_API_SECRET}
  mmux-vite-web:
    image: simcore/services/dynamic/mmux-vite-web:1.0.0
  mmux-vite-app:
    image: simcore/services/dynamic/mmux-vite-app:1.0.0
    environment:
      - WEB_SERVICE=mmux-vite-web:8080
      - BACKEND_SERVICE=mmux-vite-backend:5000
    ports:
      - "8888:8888"
    depends_on:
      - mmux-vite-backend
      - mmux-vite-web