# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.response_register_function_job_v0_function_jobs_post import ResponseRegisterFunctionJobV0FunctionJobsPost

class TestResponseRegisterFunctionJobV0FunctionJobsPost(unittest.TestCase):
    """ResponseRegisterFunctionJobV0FunctionJobsPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseRegisterFunctionJobV0FunctionJobsPost:
        """Test ResponseRegisterFunctionJobV0FunctionJobsPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseRegisterFunctionJobV0FunctionJobsPost`
        """
        model = ResponseRegisterFunctionJobV0FunctionJobsPost()
        if include_optional:
            return ResponseRegisterFunctionJobV0FunctionJobsPost(
                title = '',
                description = '',
                function_uid = '',
                inputs = osparc_client.models.inputs.inputs(),
                outputs = osparc_client.models.outputs.outputs(),
                function_class = 'SOLVER',
                uid = '',
                project_job_id = '',
                solver_job_id = ''
            )
        else:
            return ResponseRegisterFunctionJobV0FunctionJobsPost(
                function_uid = '',
                inputs = osparc_client.models.inputs.inputs(),
                outputs = osparc_client.models.outputs.outputs(),
                uid = '',
                project_job_id = '',
                solver_job_id = '',
        )
        """

    def testResponseRegisterFunctionJobV0FunctionJobsPost(self):
        """Test ResponseRegisterFunctionJobV0FunctionJobsPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
