# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.project_function import ProjectFunction

class TestProjectFunction(unittest.TestCase):
    """ProjectFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectFunction:
        """Test ProjectFunction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectFunction`
        """
        model = ProjectFunction()
        if include_optional:
            return ProjectFunction(
                function_class = 'PROJECT',
                title = '',
                description = '',
                input_schema = None,
                output_schema = None,
                default_inputs = None,
                project_id = ''
            )
        else:
            return ProjectFunction(
                input_schema = None,
                output_schema = None,
                default_inputs = None,
                project_id = '',
        )
        """

    def testProjectFunction(self):
        """Test ProjectFunction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
