# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.registered_python_code_function import RegisteredPythonCodeFunction

class TestRegisteredPythonCodeFunction(unittest.TestCase):
    """RegisteredPythonCodeFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisteredPythonCodeFunction:
        """Test RegisteredPythonCodeFunction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisteredPythonCodeFunction`
        """
        model = RegisteredPythonCodeFunction()
        if include_optional:
            return RegisteredPythonCodeFunction(
                function_class = 'PYTHON_CODE',
                title = '',
                description = '',
                input_schema = None,
                output_schema = None,
                default_inputs = None,
                uid = '',
                code_url = ''
            )
        else:
            return RegisteredPythonCodeFunction(
                input_schema = None,
                output_schema = None,
                default_inputs = None,
                uid = '',
                code_url = '',
        )
        """

    def testRegisteredPythonCodeFunction(self):
        """Test RegisteredPythonCodeFunction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
