# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.registered_function_job_collection import RegisteredFunctionJobCollection

class TestRegisteredFunctionJobCollection(unittest.TestCase):
    """RegisteredFunctionJobCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisteredFunctionJobCollection:
        """Test RegisteredFunctionJobCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisteredFunctionJobCollection`
        """
        model = RegisteredFunctionJobCollection()
        if include_optional:
            return RegisteredFunctionJobCollection(
                title = '',
                description = '',
                job_ids = [
                    ''
                    ],
                uid = ''
            )
        else:
            return RegisteredFunctionJobCollection(
                uid = '',
        )
        """

    def testRegisteredFunctionJobCollection(self):
        """Test RegisteredFunctionJobCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
