# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.response_get_function_inputschema_v0_functions_function_id_input_schema_get import ResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet

class TestResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet(unittest.TestCase):
    """ResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet:
        """Test ResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet`
        """
        model = ResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet()
        if include_optional:
            return ResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet(
                schema_content = osparc_client.models.json_schema.JSON Schema(),
                schema_class = 'application/schema+json'
            )
        else:
            return ResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet(
        )
        """

    def testResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet(self):
        """Test ResponseGetFunctionInputschemaV0FunctionsFunctionIdInputSchemaGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
