/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetadataValue } from '../models/MetadataValue';
import { HttpFile } from '../http/http';

export class JobMetadataUpdate {
    /**
    * Custom key-value map
    */
    'metadata'?: { [key: string]: MetadataValue; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: MetadataValue; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobMetadataUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}
