/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LicensedItemCheckoutGet {
    'licensedItemCheckoutId': string;
    'licensedItemId': string;
    'key': string;
    'version': string;
    'walletId': number;
    'userId': number;
    'productName': string;
    'startedAt': Date;
    'stoppedAt': Date | null;
    'numOfSeats': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "licensedItemCheckoutId",
            "baseName": "licensed_item_checkout_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "licensedItemId",
            "baseName": "licensed_item_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "walletId",
            "baseName": "wallet_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "startedAt",
            "baseName": "started_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "stoppedAt",
            "baseName": "stopped_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "numOfSeats",
            "baseName": "num_of_seats",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LicensedItemCheckoutGet.attributeTypeMap;
    }

    public constructor() {
    }
}
