/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LicensedResource } from '../models/LicensedResource';
import { LicensedResourceType } from '../models/LicensedResourceType';
import { HttpFile } from '../http/http';

export class LicensedItemGet {
    'licensedItemId': string;
    'key': string;
    'version': string;
    'displayName': string;
    'licensedResourceType': LicensedResourceType;
    'licensedResources': Array<LicensedResource>;
    'pricingPlanId': number;
    'isHiddenOnMarket': boolean;
    'createdAt': Date;
    'modifiedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "licensedItemId",
            "baseName": "licensed_item_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "licensedResourceType",
            "baseName": "licensed_resource_type",
            "type": "LicensedResourceType",
            "format": ""
        },
        {
            "name": "licensedResources",
            "baseName": "licensed_resources",
            "type": "Array<LicensedResource>",
            "format": ""
        },
        {
            "name": "pricingPlanId",
            "baseName": "pricing_plan_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "isHiddenOnMarket",
            "baseName": "is_hidden_on_market",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "modifiedAt",
            "baseName": "modified_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return LicensedItemGet.attributeTypeMap;
    }

    public constructor() {
    }
}


