/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Links {
    'first': string | null;
    'last': string | null;
    'self': string | null;
    'next': string | null;
    'prev': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "first",
            "baseName": "first",
            "type": "string",
            "format": ""
        },
        {
            "name": "last",
            "baseName": "last",
            "type": "string",
            "format": ""
        },
        {
            "name": "self",
            "baseName": "self",
            "type": "string",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string",
            "format": ""
        },
        {
            "name": "prev",
            "baseName": "prev",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Links.attributeTypeMap;
    }

    public constructor() {
    }
}
