/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserFileToProgramJob {
    /**
    * File name
    */
    'filename': string;
    /**
    * File size in bytes
    */
    'filesize': number;
    /**
    * SHA256 checksum
    */
    'sha256Checksum': string;
    /**
    * Program identifier
    */
    'programKey': string;
    /**
    * Program version
    */
    'programVersion': string;
    /**
    * Job identifier
    */
    'jobId': string;
    /**
    * The file\'s relative path within the job\'s workspace directory. E.g. \'workspace/myfile.txt\'
    */
    'workspacePath': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "filesize",
            "baseName": "filesize",
            "type": "number",
            "format": ""
        },
        {
            "name": "sha256Checksum",
            "baseName": "sha256_checksum",
            "type": "string",
            "format": ""
        },
        {
            "name": "programKey",
            "baseName": "program_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "programVersion",
            "baseName": "program_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "workspacePath",
            "baseName": "workspace_path",
            "type": "string",
            "format": "path"
        }    ];

    static getAttributeTypeMap() {
        return UserFileToProgramJob.attributeTypeMap;
    }

    public constructor() {
    }
}
