/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelFile } from '../models/ModelFile';
import { HttpFile } from '../http/http';

export class ValuesValue {
    /**
    * Resource identifier
    */
    'id': string;
    /**
    * Name of the file with extension
    */
    'filename': string;
    'contentType'?: string;
    'checksum'?: string;
    'eTag'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "checksum",
            "baseName": "checksum",
            "type": "string",
            "format": ""
        },
        {
            "name": "eTag",
            "baseName": "e_tag",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValuesValue.attributeTypeMap;
    }

    public constructor() {
    }
}
