/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.8.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectFunction } from '../models/ProjectFunction';
import { PythonCodeFunction } from '../models/PythonCodeFunction';
import { SolverFunction } from '../models/SolverFunction';
import { HttpFile } from '../http/http';

/**
 * @type Function
 * Type
 * @export
 */
export type Function = ProjectFunction | PythonCodeFunction | SolverFunction;

/**
* @type FunctionClass
* @export
*/
export class FunctionClass {
    static readonly discriminator: string | undefined = "functionClass";

    static readonly mapping: {[index: string]: string} | undefined = {
        "PROJECT": "ProjectFunction",
        "PYTHON_CODE": "PythonCodeFunction",
        "SOLVER": "SolverFunction",
    };
}


