/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.8.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectFunctionJob } from '../models/ProjectFunctionJob';
import { PythonCodeFunctionJob } from '../models/PythonCodeFunctionJob';
import { SolverFunctionJob } from '../models/SolverFunctionJob';
import { HttpFile } from '../http/http';

/**
 * @type FunctionJob
 * Type
 * @export
 */
export type FunctionJob = ProjectFunctionJob | PythonCodeFunctionJob | SolverFunctionJob;

/**
* @type FunctionJobClass
* @export
*/
export class FunctionJobClass {
    static readonly discriminator: string | undefined = "functionClass";

    static readonly mapping: {[index: string]: string} | undefined = {
        "PROJECT": "ProjectFunctionJob",
        "PYTHON_CODE": "PythonCodeFunctionJob",
        "SOLVER": "SolverFunctionJob",
    };
}


