/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.8.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetCreditPriceLegacy {
    'productName': string;
    'usdPerCredit': number | null;
    'minPaymentAmountUsd': number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productName",
            "baseName": "productName",
            "type": "string",
            "format": ""
        },
        {
            "name": "usdPerCredit",
            "baseName": "usdPerCredit",
            "type": "number",
            "format": ""
        },
        {
            "name": "minPaymentAmountUsd",
            "baseName": "minPaymentAmountUsd",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCreditPriceLegacy.attributeTypeMap;
    }

    public constructor() {
    }
}
