/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.8.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UsersGroup } from '../models/UsersGroup';
import { HttpFile } from '../http/http';

export class Groups {
    'me': UsersGroup;
    'organizations'?: Array<UsersGroup> | null;
    'all': UsersGroup;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "me",
            "baseName": "me",
            "type": "UsersGroup",
            "format": ""
        },
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<UsersGroup>",
            "format": ""
        },
        {
            "name": "all",
            "baseName": "all",
            "type": "UsersGroup",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Groups.attributeTypeMap;
    }

    public constructor() {
    }
}
