/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.8.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JobLog {
    'jobId': string;
    'nodeId'?: string | null;
    'logLevel': number;
    'messages': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "nodeId",
            "baseName": "node_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "logLevel",
            "baseName": "log_level",
            "type": "number",
            "format": ""
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobLog.attributeTypeMap;
    }

    public constructor() {
    }
}
