/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.8.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingPlanClassification } from '../models/PricingPlanClassification';
import { PricingUnitGetLegacy } from '../models/PricingUnitGetLegacy';
import { HttpFile } from '../http/http';

export class ServicePricingPlanGetLegacy {
    'pricingPlanId': number;
    'displayName': string;
    'description': string;
    'classification': PricingPlanClassification;
    'createdAt': Date;
    'pricingPlanKey': string;
    'pricingUnits': Array<PricingUnitGetLegacy>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pricingPlanId",
            "baseName": "pricingPlanId",
            "type": "number",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "classification",
            "baseName": "classification",
            "type": "PricingPlanClassification",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "pricingPlanKey",
            "baseName": "pricingPlanKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "pricingUnits",
            "baseName": "pricingUnits",
            "type": "Array<PricingUnitGetLegacy>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServicePricingPlanGetLegacy.attributeTypeMap;
    }

    public constructor() {
    }
}


