"""
Regression test for SPEC.md B4/V3: local-dev compose files must gate the
Caddy proxy (`mmux-vite-app`) on `condition: service_healthy` for both
upstream services, not just container start, or it serves traffic before
`mmux-vite-backend`/`mmux-vite-web` pass their HEALTHCHECK
(30s interval, 20s start-period) — producing transient
"no upstreams available" 503s on every local stack (re)start.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# docker-compose.yml is regenerated by `ooil compose` (SPEC.md V7) and already
# emits `condition: service_healthy` for these upstreams; only the
# hand-maintained dev-convenience files can drift.
COMPOSE_FILES = [
    "docker-compose-development.yml",
    "docker-compose-local.yml",
]


def test_app_service_depends_on_healthy_upstreams():
    for filename in COMPOSE_FILES:
        content = (REPO_ROOT / filename).read_text()

        depends_on_idx = content.index("depends_on:")
        depends_on_block = content[depends_on_idx : depends_on_idx + 200]

        assert "mmux-vite-backend" in depends_on_block, (
            f"{filename}: mmux-vite-app depends_on must list mmux-vite-backend"
        )
        assert "mmux-vite-web" in depends_on_block, (
            f"{filename}: mmux-vite-app depends_on must list mmux-vite-web"
        )
        assert depends_on_block.count("condition: service_healthy") == 2, (
            f"{filename}: mmux-vite-app depends_on must use "
            "`condition: service_healthy` for both mmux-vite-backend and "
            "mmux-vite-web (V3) — plain list-form depends_on only waits for "
            "container start, not health (B4)"
        )
