"""
Regression test for SPEC.md B4/V3: local-dev compose files must gate the
Caddy proxy (`mmux-vite-app`) on `condition: service_healthy` for both
upstream services, not just container start, or it serves traffic before
`mmux-vite-backend`/`mmux-vite-web` pass their HEALTHCHECK
(30s interval, 20s start-period) — producing transient
"no upstreams available" 503s on every local stack (re)start.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# docker-compose.yml is regenerated by `ooil compose` (SPEC.md V7) and already
# emits `condition: service_healthy` for these upstreams; only the
# hand-maintained dev-convenience files can drift.
COMPOSE_FILES = [
    "docker-compose-development.yml",
    "docker-compose-local.yml",
]

VITE_CONFIG = REPO_ROOT / "node" / "vite.config.ts"


def test_app_service_depends_on_healthy_upstreams():
    for filename in COMPOSE_FILES:
        content = (REPO_ROOT / filename).read_text()

        depends_on_idx = content.index("depends_on:")
        depends_on_block = content[depends_on_idx : depends_on_idx + 200]

        assert "mmux-vite-backend" in depends_on_block, (
            f"{filename}: mmux-vite-app depends_on must list mmux-vite-backend"
        )
        assert "mmux-vite-web" in depends_on_block, (
            f"{filename}: mmux-vite-app depends_on must list mmux-vite-web"
        )
        assert depends_on_block.count("condition: service_healthy") == 2, (
            f"{filename}: mmux-vite-app depends_on must use "
            "`condition: service_healthy` for both mmux-vite-backend and "
            "mmux-vite-web (V3) — plain list-form depends_on only waits for "
            "container start, not health (B4)"
        )


def test_vite_dev_server_does_not_force_internal_origin():
    content = VITE_CONFIG.read_text()

    assert "origin:" not in content, (
        "node/vite.config.ts: Vite dev server must derive its browser origin "
        "from the request host so docker-compose APP_PORT fallback ports keep "
        "serving dev assets/HMR through Caddy (V17/B5)"
    )
    assert "clientPort: appPort" in content, (
        "node/vite.config.ts: Vite HMR must use APP_PORT as the browser-facing "
        "client port instead of the internal 8080 dev-server port (V17/B5)"
    )


def test_development_compose_passes_app_port_to_vite():
    content = (REPO_ROOT / "docker-compose-development.yml").read_text()

    assert "APP_PORT=${APP_PORT:-8888}" in content, (
        "docker-compose-development.yml: mmux-vite-web must receive APP_PORT "
        "so Vite can advertise the same browser-facing port printed by the "
        "Makefile fallback logic (V17/B5)"
    )
