/**
 * Swagger Functions Store - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerFunctionsStoreOpenApi30);
  }
}(this, function(expect, SwaggerFunctionsStoreOpenApi30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerFunctionsStoreOpenApi30.FunctionJob();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FunctionJob', function() {
    it('should create an instance of FunctionJob', function() {
      // uncomment below and update the code to test FunctionJob
      //var instance = new SwaggerFunctionsStoreOpenApi30.FunctionJob();
      //expect(instance).to.be.a(SwaggerFunctionsStoreOpenApi30.FunctionJob);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SwaggerFunctionsStoreOpenApi30.FunctionJob();
      //expect(instance).to.be();
    });

    it('should have the property functionID (base name: "functionID")', function() {
      // uncomment below and update the code to test the property functionID
      //var instance = new SwaggerFunctionsStoreOpenApi30.FunctionJob();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new SwaggerFunctionsStoreOpenApi30.FunctionJob();
      //expect(instance).to.be();
    });

    it('should have the property inputs (base name: "inputs")', function() {
      // uncomment below and update the code to test the property inputs
      //var instance = new SwaggerFunctionsStoreOpenApi30.FunctionJob();
      //expect(instance).to.be();
    });

    it('should have the property outputs (base name: "outputs")', function() {
      // uncomment below and update the code to test the property outputs
      //var instance = new SwaggerFunctionsStoreOpenApi30.FunctionJob();
      //expect(instance).to.be();
    });

    it('should have the property jobInfo (base name: "job_info")', function() {
      // uncomment below and update the code to test the property jobInfo
      //var instance = new SwaggerFunctionsStoreOpenApi30.FunctionJob();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new SwaggerFunctionsStoreOpenApi30.FunctionJob();
      //expect(instance).to.be();
    });

  });

}));
