/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClientFile } from '../models/ClientFile';
import { HttpFile } from '../http/http';

export class BodyAbortMultipartUploadV0FilesFileIdAbortPost {
    'clientFile': ClientFile;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clientFile",
            "baseName": "client_file",
            "type": "ClientFile",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BodyAbortMultipartUploadV0FilesFileIdAbortPost.attributeTypeMap;
    }

    public constructor() {
    }
}
