/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FileUploadData } from '../models/FileUploadData';
import { HttpFile } from '../http/http';

export class ClientFileUploadData {
    /**
    * The file resource id
    */
    'fileId': string;
    /**
    * Schema for uploading file
    */
    'uploadSchema': FileUploadData;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fileId",
            "baseName": "file_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "uploadSchema",
            "baseName": "upload_schema",
            "type": "FileUploadData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientFileUploadData.attributeTypeMap;
    }

    public constructor() {
    }
}
