/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.8.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UploadLinks } from '../models/UploadLinks';
import { HttpFile } from '../http/http';

export class FileUploadData {
    'chunkSize': number;
    'urls': Array<string>;
    'links': UploadLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chunkSize",
            "baseName": "chunk_size",
            "type": "number",
            "format": ""
        },
        {
            "name": "urls",
            "baseName": "urls",
            "type": "Array<string>",
            "format": "uri"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "UploadLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FileUploadData.attributeTypeMap;
    }

    public constructor() {
    }
}
