/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JSONFunctionInputSchema } from '../models/JSONFunctionInputSchema';
import { HttpFile } from '../http/http';

/**
 * @type InputSchema
 * Type
 * @export
 */
export type InputSchema = JSONFunctionInputSchema;

/**
* @type InputSchemaClass
* @export
*/
export class InputSchemaClass {
    static readonly discriminator: string | undefined = "schemaClass";

    static readonly mapping: {[index: string]: string} | undefined = {
        "application/schema+json": "JSONFunctionInputSchema",
    };
}
