/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LogLink } from '../models/LogLink';
import { HttpFile } from '../http/http';

export class JobLogsMap {
    /**
    * Array of download links
    */
    'logLinks': Array<LogLink>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "logLinks",
            "baseName": "log_links",
            "type": "Array<LogLink>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobLogsMap.attributeTypeMap;
    }

    public constructor() {
    }
}
