/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetadataValue } from '../models/MetadataValue';
import { HttpFile } from '../http/http';

export class JobMetadata {
    /**
    * Parent Job
    */
    'jobId': string;
    /**
    * Custom key-value map
    */
    'metadata': { [key: string]: MetadataValue; };
    'url': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: MetadataValue; }",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return JobMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}
