/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValuesValue } from '../models/ValuesValue';
import { HttpFile } from '../http/http';

export class JobOutputs {
    /**
    * Job that produced this output
    */
    'jobId': string;
    'results': { [key: string]: ValuesValue; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "{ [key: string]: ValuesValue; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobOutputs.attributeTypeMap;
    }

    public constructor() {
    }
}
