/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RunningState } from '../models/RunningState';
import { HttpFile } from '../http/http';

export class JobStatus {
    'jobId': string;
    'state': RunningState;
    'progress'?: number;
    /**
    * Last modification timestamp of the solver job
    */
    'submittedAt': Date;
    'startedAt'?: Date | null;
    'stoppedAt'?: Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "RunningState",
            "format": ""
        },
        {
            "name": "progress",
            "baseName": "progress",
            "type": "number",
            "format": ""
        },
        {
            "name": "submittedAt",
            "baseName": "submitted_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "startedAt",
            "baseName": "started_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "stoppedAt",
            "baseName": "stopped_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return JobStatus.attributeTypeMap;
    }

    public constructor() {
    }
}


