/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JSONFunctionOutputSchema {
    /**
    * JSON Schema
    */
    'schemaContent'?: any;
    'schemaClass'?: JSONFunctionOutputSchemaSchemaClassEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schemaContent",
            "baseName": "schema_content",
            "type": "any",
            "format": ""
        },
        {
            "name": "schemaClass",
            "baseName": "schema_class",
            "type": "JSONFunctionOutputSchemaSchemaClassEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JSONFunctionOutputSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum JSONFunctionOutputSchemaSchemaClassEnum {
    ApplicationSchemajson = 'application/schema+json'
}

