/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LicensedResourceSourceFeaturesDict {
    'age'?: string;
    'date': string;
    'ethnicity'?: string;
    'functionality'?: string;
    'height'?: string;
    'name'?: string;
    'sex'?: string;
    'species'?: string;
    'version'?: string;
    'weight'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "age",
            "baseName": "age",
            "type": "string",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "ethnicity",
            "baseName": "ethnicity",
            "type": "string",
            "format": ""
        },
        {
            "name": "functionality",
            "baseName": "functionality",
            "type": "string",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "sex",
            "baseName": "sex",
            "type": "string",
            "format": ""
        },
        {
            "name": "species",
            "baseName": "species",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LicensedResourceSourceFeaturesDict.attributeTypeMap;
    }

    public constructor() {
    }
}
