/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LicensedResourceSource } from '../models/LicensedResourceSource';
import { HttpFile } from '../http/http';

export class LicensedResource {
    'source': LicensedResourceSource;
    'categoryId': string;
    'categoryDisplay': string;
    'termsOfUseUrl': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "source",
            "baseName": "source",
            "type": "LicensedResourceSource",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryDisplay",
            "baseName": "category_display",
            "type": "string",
            "format": ""
        },
        {
            "name": "termsOfUseUrl",
            "baseName": "terms_of_use_url",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return LicensedResource.attributeTypeMap;
    }

    public constructor() {
    }
}
