/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Meta {
    'name': string;
    'version': string;
    'released'?: { [key: string]: string; } | null;
    'docsUrl': string;
    'docsDevUrl': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "released",
            "baseName": "released",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "docsUrl",
            "baseName": "docs_url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "docsDevUrl",
            "baseName": "docs_dev_url",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return Meta.attributeTypeMap;
    }

    public constructor() {
    }
}
