/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JSONFunctionOutputSchema } from '../models/JSONFunctionOutputSchema';
import { HttpFile } from '../http/http';

/**
 * @type OutputSchema
 * Type
 * @export
 */
export type OutputSchema = JSONFunctionOutputSchema;

/**
* @type OutputSchemaClass
* @export
*/
export class OutputSchemaClass {
    static readonly discriminator: string | undefined = "schemaClass";

    static readonly mapping: {[index: string]: string} | undefined = {
        "application/schema+json": "JSONFunctionOutputSchema",
    };
}
