/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UnitExtraInfoTier } from '../models/UnitExtraInfoTier';
import { HttpFile } from '../http/http';

export class PricingUnitGetLegacy {
    'pricingUnitId': number;
    'unitName': string;
    'unitExtraInfo': UnitExtraInfoTier;
    'currentCostPerUnit': number;
    '_default': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pricingUnitId",
            "baseName": "pricingUnitId",
            "type": "number",
            "format": ""
        },
        {
            "name": "unitName",
            "baseName": "unitName",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitExtraInfo",
            "baseName": "unitExtraInfo",
            "type": "UnitExtraInfoTier",
            "format": ""
        },
        {
            "name": "currentCostPerUnit",
            "baseName": "currentCostPerUnit",
            "type": "number",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PricingUnitGetLegacy.attributeTypeMap;
    }

    public constructor() {
    }
}
