/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.8.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A released program with a specific version
*/
export class Program {
    /**
    * Resource identifier
    */
    'id': string;
    /**
    * Semantic version number of the resource
    */
    'version': string;
    /**
    * Human readable name
    */
    'title': string;
    'description'?: string | null;
    'url': string | null;
    'versionDisplay': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "versionDisplay",
            "baseName": "version_display",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Program.attributeTypeMap;
    }

    public constructor() {
    }
}
