/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProjectFunctionJob {
    'uid': string; // added to TypeScript  
    'title'?: string;
    'description'?: string;
    'functionUid': string;
    'inputs': any | null;
    'outputs': any | null;
    'functionClass'?: ProjectFunctionJobFunctionClassEnum;
    'projectJobId': string;
    'status': string; // added to TypeScript stubs for consistency. Being fetched in the Python backend.

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "functionUid",
            "baseName": "function_uid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "any",
            "format": ""
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "any",
            "format": ""
        },
        {
            "name": "functionClass",
            "baseName": "function_class",
            "type": "ProjectFunctionJobFunctionClassEnum",
            "format": ""
        },
        {
            "name": "projectJobId",
            "baseName": "project_job_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return ProjectFunctionJob.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProjectFunctionJobFunctionClassEnum {
    Project = 'PROJECT'
}

