/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InputSchema } from '../models/InputSchema';
import { OutputSchema } from '../models/OutputSchema';
import { HttpFile } from '../http/http';

export class RegisteredProjectFunction {
    'functionClass'?: RegisteredProjectFunctionFunctionClassEnum;
    'title'?: string;
    'description'?: string;
    'inputSchema': InputSchema;
    'outputSchema': OutputSchema;
    'defaultInputs': any | null;
    'uid': string;
    'projectId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functionClass",
            "baseName": "function_class",
            "type": "RegisteredProjectFunctionFunctionClassEnum",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "inputSchema",
            "baseName": "input_schema",
            "type": "InputSchema",
            "format": ""
        },
        {
            "name": "outputSchema",
            "baseName": "output_schema",
            "type": "OutputSchema",
            "format": ""
        },
        {
            "name": "defaultInputs",
            "baseName": "default_inputs",
            "type": "any",
            "format": ""
        },
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "projectId",
            "baseName": "project_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return RegisteredProjectFunction.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum RegisteredProjectFunctionFunctionClassEnum {
    Project = 'PROJECT'
}

