/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RegisteredProjectFunctionJob } from '../models/RegisteredProjectFunctionJob';
import { RegisteredPythonCodeFunctionJob } from '../models/RegisteredPythonCodeFunctionJob';
import { RegisteredSolverFunctionJob } from '../models/RegisteredSolverFunctionJob';
import { HttpFile } from '../http/http';

/**
 * @type ResponseRegisterFunctionJobV0FunctionJobsPost
 * Type
 * @export
 */
export type ResponseRegisterFunctionJobV0FunctionJobsPost = RegisteredProjectFunctionJob | RegisteredPythonCodeFunctionJob | RegisteredSolverFunctionJob;

/**
* @type ResponseRegisterFunctionJobV0FunctionJobsPostClass
* @export
*/
export class ResponseRegisterFunctionJobV0FunctionJobsPostClass {
    static readonly discriminator: string | undefined = "functionClass";

    static readonly mapping: {[index: string]: string} | undefined = {
        "PROJECT": "RegisteredProjectFunctionJob",
        "PYTHON_CODE": "RegisteredPythonCodeFunctionJob",
        "SOLVER": "RegisteredSolverFunctionJob",
    };
}


