/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* State of execution of a project\'s computational workflow  SEE StateType for task state
*/
export enum RunningState {
    Unknown = 'UNKNOWN',
    Published = 'PUBLISHED',
    NotStarted = 'NOT_STARTED',
    Pending = 'PENDING',
    WaitingForResources = 'WAITING_FOR_RESOURCES',
    Started = 'STARTED',
    Success = 'SUCCESS',
    Failed = 'FAILED',
    Aborted = 'ABORTED',
    WaitingForCluster = 'WAITING_FOR_CLUSTER'
}
