/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SolverPort {
    /**
    * port identifier name
    */
    'key': string;
    'kind': SolverPortKindEnum;
    'contentSchema'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "SolverPortKindEnum",
            "format": ""
        },
        {
            "name": "contentSchema",
            "baseName": "content_schema",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SolverPort.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SolverPortKindEnum {
    Input = 'input',
    Output = 'output'
}

