/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StudyPort {
    /**
    * port identifier name.Correponds to the UUID of the parameter/probe node in the study
    */
    'key': string;
    'kind': StudyPortKindEnum;
    'contentSchema'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "StudyPortKindEnum",
            "format": ""
        },
        {
            "name": "contentSchema",
            "baseName": "content_schema",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StudyPort.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum StudyPortKindEnum {
    Input = 'input',
    Output = 'output'
}

