/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.0.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Custom information that is propagated to the frontend. Defined fields are mandatory.
*/
export class UnitExtraInfoTier {
    'CPU': number;
    'RAM': number;
    'VRAM': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "CPU",
            "baseName": "CPU",
            "type": "number",
            "format": ""
        },
        {
            "name": "RAM",
            "baseName": "RAM",
            "type": "number",
            "format": ""
        },
        {
            "name": "VRAM",
            "baseName": "VRAM",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UnitExtraInfoTier.attributeTypeMap;
    }

    public constructor() {
    }
}
