/**
 * osparc.io public API
 * osparc-simcore public API specifications
 *
 * OpenAPI spec version: 0.7.1.post0.dev0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WalletStatus } from '../models/WalletStatus';
import { HttpFile } from '../http/http';

export class WalletGetWithAvailableCreditsLegacy {
    'walletId': number;
    'name': string;
    'description'?: string | null;
    'owner': number;
    'thumbnail'?: string | null;
    'status': WalletStatus;
    'created': Date;
    'modified': Date;
    'availableCredits': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "walletId",
            "baseName": "walletId",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "number",
            "format": ""
        },
        {
            "name": "thumbnail",
            "baseName": "thumbnail",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "WalletStatus",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "modified",
            "baseName": "modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "availableCredits",
            "baseName": "availableCredits",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WalletGetWithAvailableCreditsLegacy.attributeTypeMap;
    }

    public constructor() {
    }
}


