# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.response200_get_log_stream_v0_solvers_solver_key_releases_version_jobs_job_id_logstream_get import Response200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet

class TestResponse200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet(unittest.TestCase):
    """Response200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Response200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet:
        """Test Response200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Response200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet`
        """
        model = Response200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet()
        if include_optional:
            return Response200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet(
                job_id = '',
                node_id = '',
                log_level = 56,
                messages = [
                    ''
                    ],
                errors = [
                    null
                    ]
            )
        else:
            return Response200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet(
                job_id = '',
                log_level = 56,
                messages = [
                    ''
                    ],
                errors = [
                    null
                    ],
        )
        """

    def testResponse200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet(self):
        """Test Response200GetLogStreamV0SolversSolverKeyReleasesVersionJobsJobIdLogstreamGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
