# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.function_job_collections_api import FunctionJobCollectionsApi


class TestFunctionJobCollectionsApi(unittest.TestCase):
    """FunctionJobCollectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FunctionJobCollectionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_function_job_collection(self) -> None:
        """Test case for delete_function_job_collection

        Delete Function Job Collection
        """
        pass

    def test_function_job_collection_list_function_jobs(self) -> None:
        """Test case for function_job_collection_list_function_jobs

        Function Job Collection List Function Jobs
        """
        pass

    def test_function_job_collection_status(self) -> None:
        """Test case for function_job_collection_status

        Function Job Collection Status
        """
        pass

    def test_get_function_job_collection(self) -> None:
        """Test case for get_function_job_collection

        Get Function Job Collection
        """
        pass

    def test_list_function_job_collections(self) -> None:
        """Test case for list_function_job_collections

        List Function Job Collections
        """
        pass

    def test_register_function_job_collection(self) -> None:
        """Test case for register_function_job_collection

        Register Function Job Collection
        """
        pass


if __name__ == '__main__':
    unittest.main()
