# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.pricing_plan_classification import PricingPlanClassification

class TestPricingPlanClassification(unittest.TestCase):
    """PricingPlanClassification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPricingPlanClassification(self):
        """Test PricingPlanClassification"""
        # inst = PricingPlanClassification()

if __name__ == '__main__':
    unittest.main()
