# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.licensed_item_checkout_get import LicensedItemCheckoutGet

class TestLicensedItemCheckoutGet(unittest.TestCase):
    """LicensedItemCheckoutGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LicensedItemCheckoutGet:
        """Test LicensedItemCheckoutGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LicensedItemCheckoutGet`
        """
        model = LicensedItemCheckoutGet()
        if include_optional:
            return LicensedItemCheckoutGet(
                licensed_item_checkout_id = '',
                licensed_item_id = '',
                key = '',
                version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026',
                wallet_id = 0,
                user_id = 0,
                product_name = '',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                stopped_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                num_of_seats = 56
            )
        else:
            return LicensedItemCheckoutGet(
                licensed_item_checkout_id = '',
                licensed_item_id = '',
                key = '',
                version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026',
                wallet_id = 0,
                user_id = 0,
                product_name = '',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                stopped_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                num_of_seats = 56,
        )
        """

    def testLicensedItemCheckoutGet(self):
        """Test LicensedItemCheckoutGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
