# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.studies_api import StudiesApi


class TestStudiesApi(unittest.TestCase):
    """StudiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StudiesApi()

    def tearDown(self) -> None:
        pass

    def test_clone_study(self) -> None:
        """Test case for clone_study

        Clone Study
        """
        pass

    def test_create_study_job(self) -> None:
        """Test case for create_study_job

        Create Study Job
        """
        pass

    def test_delete_study_job(self) -> None:
        """Test case for delete_study_job

        Delete Study Job
        """
        pass

    def test_get_study(self) -> None:
        """Test case for get_study

        Get Study
        """
        pass

    def test_get_study_job_custom_metadata(self) -> None:
        """Test case for get_study_job_custom_metadata

        Get Study Job Custom Metadata
        """
        pass

    def test_get_study_job_output_logfile(self) -> None:
        """Test case for get_study_job_output_logfile

        Get download links for study job log files
        """
        pass

    def test_get_study_job_outputs(self) -> None:
        """Test case for get_study_job_outputs

        Get Study Job Outputs
        """
        pass

    def test_inspect_study_job(self) -> None:
        """Test case for inspect_study_job

        Inspect Study Job
        """
        pass

    def test_list_studies(self) -> None:
        """Test case for list_studies

        List Studies
        """
        pass

    def test_list_study_ports(self) -> None:
        """Test case for list_study_ports

        List Study Ports
        """
        pass

    def test_replace_study_job_custom_metadata(self) -> None:
        """Test case for replace_study_job_custom_metadata

        Replace Study Job Custom Metadata
        """
        pass

    def test_start_study_job(self) -> None:
        """Test case for start_study_job

        Start Study Job
        """
        pass

    def test_stop_study_job(self) -> None:
        """Test case for stop_study_job

        Stop Study Job
        """
        pass


if __name__ == '__main__':
    unittest.main()
