# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.python_code_function import PythonCodeFunction

class TestPythonCodeFunction(unittest.TestCase):
    """PythonCodeFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PythonCodeFunction:
        """Test PythonCodeFunction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PythonCodeFunction`
        """
        model = PythonCodeFunction()
        if include_optional:
            return PythonCodeFunction(
                function_class = 'PYTHON_CODE',
                title = '',
                description = '',
                input_schema = osparc_client.models.json_function_input_schema.JSONFunctionInputSchema(
                    schema_content = osparc_client.models.json_schema.JSON Schema(), 
                    schema_class = 'application/schema+json', ),
                output_schema = osparc_client.models.json_function_output_schema.JSONFunctionOutputSchema(
                    schema_content = osparc_client.models.json_schema.JSON Schema(), 
                    schema_class = 'application/schema+json', ),
                default_inputs = None,
                code_url = ''
            )
        else:
            return PythonCodeFunction(
                input_schema = osparc_client.models.json_function_input_schema.JSONFunctionInputSchema(
                    schema_content = osparc_client.models.json_schema.JSON Schema(), 
                    schema_class = 'application/schema+json', ),
                output_schema = osparc_client.models.json_function_output_schema.JSONFunctionOutputSchema(
                    schema_content = osparc_client.models.json_schema.JSON Schema(), 
                    schema_class = 'application/schema+json', ),
                default_inputs = None,
                code_url = '',
        )
        """

    def testPythonCodeFunction(self):
        """Test PythonCodeFunction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
