# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.one_page_solver_port import OnePageSolverPort

class TestOnePageSolverPort(unittest.TestCase):
    """OnePageSolverPort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnePageSolverPort:
        """Test OnePageSolverPort
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnePageSolverPort`
        """
        model = OnePageSolverPort()
        if include_optional:
            return OnePageSolverPort(
                items = [
                    {content_schema={maximum=5, minimum=0, title=Sleep interval, type=integer, x_unit=second}, key=input_2, kind=input}
                    ],
                total = 0
            )
        else:
            return OnePageSolverPort(
                items = [
                    {content_schema={maximum=5, minimum=0, title=Sleep interval, type=integer, x_unit=second}, key=input_2, kind=input}
                    ],
        )
        """

    def testOnePageSolverPort(self):
        """Test OnePageSolverPort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
