# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.study_port import StudyPort

class TestStudyPort(unittest.TestCase):
    """StudyPort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StudyPort:
        """Test StudyPort
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudyPort`
        """
        model = StudyPort()
        if include_optional:
            return StudyPort(
                key = '',
                kind = 'input',
                content_schema = None
            )
        else:
            return StudyPort(
                key = '',
                kind = 'input',
        )
        """

    def testStudyPort(self):
        """Test StudyPort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
