# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.files_api import FilesApi


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FilesApi()

    def tearDown(self) -> None:
        pass

    def test_abort_multipart_upload(self) -> None:
        """Test case for abort_multipart_upload

        Abort Multipart Upload
        """
        pass

    def test_complete_multipart_upload(self) -> None:
        """Test case for complete_multipart_upload

        Complete Multipart Upload
        """
        pass

    def test_delete_file(self) -> None:
        """Test case for delete_file

        Delete File
        """
        pass

    def test_download_file(self) -> None:
        """Test case for download_file

        Download File
        """
        pass

    def test_get_file(self) -> None:
        """Test case for get_file

        Get File
        """
        pass

    def test_get_files_page(self) -> None:
        """Test case for get_files_page

        Get Files Page
        """
        pass

    def test_get_upload_links(self) -> None:
        """Test case for get_upload_links

        Get Upload Links
        """
        pass

    def test_list_files(self) -> None:
        """Test case for list_files

        List Files
        """
        pass

    def test_search_files_page(self) -> None:
        """Test case for search_files_page

        Search Files Page
        """
        pass

    def test_upload_file(self) -> None:
        """Test case for upload_file

        Upload File
        """
        pass


if __name__ == '__main__':
    unittest.main()
