# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.wallets_api import WalletsApi


class TestWalletsApi(unittest.TestCase):
    """WalletsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WalletsApi()

    def tearDown(self) -> None:
        pass

    def test_checkout_licensed_item(self) -> None:
        """Test case for checkout_licensed_item

        Checkout Licensed Item
        """
        pass

    def test_get_available_licensed_items_for_wallet(self) -> None:
        """Test case for get_available_licensed_items_for_wallet

        Get Available Licensed Items For Wallet
        """
        pass

    def test_get_default_wallet(self) -> None:
        """Test case for get_default_wallet

        Get Default Wallet
        """
        pass

    def test_get_wallet(self) -> None:
        """Test case for get_wallet

        Get Wallet
        """
        pass


if __name__ == '__main__':
    unittest.main()
