# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.running_state import RunningState

class TestRunningState(unittest.TestCase):
    """RunningState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunningState(self):
        """Test RunningState"""
        # inst = RunningState()

if __name__ == '__main__':
    unittest.main()
