# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.functions_api import FunctionsApi


class TestFunctionsApi(unittest.TestCase):
    """FunctionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FunctionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_function(self) -> None:
        """Test case for delete_function

        Delete Function
        """
        pass

    def test_get_function(self) -> None:
        """Test case for get_function

        Get Function
        """
        pass

    def test_get_function_inputschema(self) -> None:
        """Test case for get_function_inputschema

        Get Function Inputschema
        """
        pass

    def test_get_function_outputschema(self) -> None:
        """Test case for get_function_outputschema

        Get Function Outputschema
        """
        pass

    def test_list_function_jobs_for_functionid(self) -> None:
        """Test case for list_function_jobs_for_functionid

        List Function Jobs For Functionid
        """
        pass

    def test_list_functions(self) -> None:
        """Test case for list_functions

        List Functions
        """
        pass

    def test_map_function(self) -> None:
        """Test case for map_function

        Map Function
        """
        pass

    def test_register_function(self) -> None:
        """Test case for register_function

        Register Function
        """
        pass

    def test_run_function(self) -> None:
        """Test case for run_function

        Run Function
        """
        pass

    def test_update_function_description(self) -> None:
        """Test case for update_function_description

        Update Function Description
        """
        pass

    def test_update_function_title(self) -> None:
        """Test case for update_function_title

        Update Function Title
        """
        pass

    def test_validate_function_inputs(self) -> None:
        """Test case for validate_function_inputs

        Validate Function Inputs
        """
        pass


if __name__ == '__main__':
    unittest.main()
