# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.body_complete_multipart_upload_v0_files_file_id_complete_post import BodyCompleteMultipartUploadV0FilesFileIdCompletePost

class TestBodyCompleteMultipartUploadV0FilesFileIdCompletePost(unittest.TestCase):
    """BodyCompleteMultipartUploadV0FilesFileIdCompletePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyCompleteMultipartUploadV0FilesFileIdCompletePost:
        """Test BodyCompleteMultipartUploadV0FilesFileIdCompletePost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyCompleteMultipartUploadV0FilesFileIdCompletePost`
        """
        model = BodyCompleteMultipartUploadV0FilesFileIdCompletePost()
        if include_optional:
            return BodyCompleteMultipartUploadV0FilesFileIdCompletePost(
                client_file = None,
                uploaded_parts = osparc_client.models.file_upload_completion_body.FileUploadCompletionBody(
                    parts = [
                        osparc_client.models.uploaded_part.UploadedPart(
                            number = 0, 
                            e_tag = '', )
                        ], )
            )
        else:
            return BodyCompleteMultipartUploadV0FilesFileIdCompletePost(
                client_file = None,
                uploaded_parts = osparc_client.models.file_upload_completion_body.FileUploadCompletionBody(
                    parts = [
                        osparc_client.models.uploaded_part.UploadedPart(
                            number = 0, 
                            e_tag = '', )
                        ], ),
        )
        """

    def testBodyCompleteMultipartUploadV0FilesFileIdCompletePost(self):
        """Test BodyCompleteMultipartUploadV0FilesFileIdCompletePost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
