# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.credits_api import CreditsApi


class TestCreditsApi(unittest.TestCase):
    """CreditsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CreditsApi()

    def tearDown(self) -> None:
        pass

    def test_get_credits_price(self) -> None:
        """Test case for get_credits_price

        Get Credits Price
        """
        pass


if __name__ == '__main__':
    unittest.main()
