# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.solvers_api import SolversApi


class TestSolversApi(unittest.TestCase):
    """SolversApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SolversApi()

    def tearDown(self) -> None:
        pass

    def test_create_solver_job(self) -> None:
        """Test case for create_solver_job

        Create Solver Job
        """
        pass

    def test_delete_job(self) -> None:
        """Test case for delete_job

        Delete Job
        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        Get Job
        """
        pass

    def test_get_job_custom_metadata(self) -> None:
        """Test case for get_job_custom_metadata

        Get Job Custom Metadata
        """
        pass

    def test_get_job_output_logfile(self) -> None:
        """Test case for get_job_output_logfile

        Get Job Output Logfile
        """
        pass

    def test_get_job_outputs(self) -> None:
        """Test case for get_job_outputs

        Get Job Outputs
        """
        pass

    def test_get_job_pricing_unit(self) -> None:
        """Test case for get_job_pricing_unit

        Get Job Pricing Unit
        """
        pass

    def test_get_job_wallet(self) -> None:
        """Test case for get_job_wallet

        Get Job Wallet
        """
        pass

    def test_get_log_stream(self) -> None:
        """Test case for get_log_stream

        Get Log Stream
        """
        pass

    def test_get_solver(self) -> None:
        """Test case for get_solver

        Get Solver
        """
        pass

    def test_get_solver_pricing_plan(self) -> None:
        """Test case for get_solver_pricing_plan

        Get Solver Pricing Plan
        """
        pass

    def test_get_solver_release(self) -> None:
        """Test case for get_solver_release

        Get Solver Release
        """
        pass

    def test_inspect_job(self) -> None:
        """Test case for inspect_job

        Inspect Job
        """
        pass

    def test_list_jobs(self) -> None:
        """Test case for list_jobs

        List Jobs
        """
        pass

    def test_list_jobs_paginated(self) -> None:
        """Test case for list_jobs_paginated

        List Jobs Paginated
        """
        pass

    def test_list_solver_ports(self) -> None:
        """Test case for list_solver_ports

        List Solver Ports
        """
        pass

    def test_list_solver_releases(self) -> None:
        """Test case for list_solver_releases

        List Solver Releases
        """
        pass

    def test_list_solvers(self) -> None:
        """Test case for list_solvers

        List Solvers
        """
        pass

    def test_list_solvers_releases(self) -> None:
        """Test case for list_solvers_releases

        Lists All Releases
        """
        pass

    def test_replace_job_custom_metadata(self) -> None:
        """Test case for replace_job_custom_metadata

        Replace Job Custom Metadata
        """
        pass

    def test_start_job(self) -> None:
        """Test case for start_job

        Start Job
        """
        pass

    def test_stop_job(self) -> None:
        """Test case for stop_job

        Stop Job
        """
        pass


if __name__ == '__main__':
    unittest.main()
