# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.response_get_function_job_v0_function_jobs_function_job_id_get import ResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet

class TestResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet(unittest.TestCase):
    """ResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet:
        """Test ResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet`
        """
        model = ResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet()
        if include_optional:
            return ResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet(
                title = '',
                description = '',
                function_uid = '',
                inputs = osparc_client.models.inputs.inputs(),
                outputs = osparc_client.models.outputs.outputs(),
                function_class = 'SOLVER',
                uid = '',
                project_job_id = '',
                solver_job_id = ''
            )
        else:
            return ResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet(
                function_uid = '',
                inputs = osparc_client.models.inputs.inputs(),
                outputs = osparc_client.models.outputs.outputs(),
                uid = '',
                project_job_id = '',
                solver_job_id = '',
        )
        """

    def testResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet(self):
        """Test ResponseGetFunctionJobV0FunctionJobsFunctionJobIdGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
