# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.profile import Profile

class TestProfile(unittest.TestCase):
    """Profile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Profile:
        """Test Profile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Profile`
        """
        model = Profile()
        if include_optional:
            return Profile(
                first_name = '',
                last_name = '',
                id = 0,
                login = '',
                role = 'ANONYMOUS',
                groups = osparc_client.models.groups.Groups(
                    me = osparc_client.models.users_group.UsersGroup(
                        gid = '', 
                        label = '', 
                        description = '', ), 
                    organizations = [
                        osparc_client.models.users_group.UsersGroup(
                            gid = '', 
                            label = '', 
                            description = '', )
                        ], 
                    all = , ),
                gravatar_id = ''
            )
        else:
            return Profile(
                id = 0,
                login = '',
                role = 'ANONYMOUS',
        )
        """

    def testProfile(self):
        """Test Profile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
