# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_get_my_profile(self) -> None:
        """Test case for get_my_profile

        Get My Profile
        """
        pass

    def test_update_my_profile(self) -> None:
        """Test case for update_my_profile

        Update My Profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
