# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.licensed_items_api import LicensedItemsApi


class TestLicensedItemsApi(unittest.TestCase):
    """LicensedItemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LicensedItemsApi()

    def tearDown(self) -> None:
        pass

    def test_get_licensed_items(self) -> None:
        """Test case for get_licensed_items

        Get Licensed Items
        """
        pass

    def test_release_licensed_item(self) -> None:
        """Test case for release_licensed_item

        Release Licensed Item
        """
        pass


if __name__ == '__main__':
    unittest.main()
