# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.response_run_function_v0_functions_function_id_run_post import ResponseRunFunctionV0FunctionsFunctionIdRunPost

class TestResponseRunFunctionV0FunctionsFunctionIdRunPost(unittest.TestCase):
    """ResponseRunFunctionV0FunctionsFunctionIdRunPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseRunFunctionV0FunctionsFunctionIdRunPost:
        """Test ResponseRunFunctionV0FunctionsFunctionIdRunPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseRunFunctionV0FunctionsFunctionIdRunPost`
        """
        model = ResponseRunFunctionV0FunctionsFunctionIdRunPost()
        if include_optional:
            return ResponseRunFunctionV0FunctionsFunctionIdRunPost(
                title = '',
                description = '',
                function_uid = '',
                inputs = osparc_client.models.inputs.inputs(),
                outputs = osparc_client.models.outputs.outputs(),
                function_class = 'SOLVER',
                uid = '',
                project_job_id = '',
                solver_job_id = ''
            )
        else:
            return ResponseRunFunctionV0FunctionsFunctionIdRunPost(
                function_uid = '',
                inputs = osparc_client.models.inputs.inputs(),
                outputs = osparc_client.models.outputs.outputs(),
                uid = '',
                project_job_id = '',
                solver_job_id = '',
        )
        """

    def testResponseRunFunctionV0FunctionsFunctionIdRunPost(self):
        """Test ResponseRunFunctionV0FunctionsFunctionIdRunPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
