# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.meta_api import MetaApi


class TestMetaApi(unittest.TestCase):
    """MetaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetaApi()

    def tearDown(self) -> None:
        pass

    def test_get_service_metadata(self) -> None:
        """Test case for get_service_metadata

        Get Service Metadata
        """
        pass


if __name__ == '__main__':
    unittest.main()
