# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.api.programs_api import ProgramsApi


class TestProgramsApi(unittest.TestCase):
    """ProgramsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProgramsApi()

    def tearDown(self) -> None:
        pass

    def test_create_program_job(self) -> None:
        """Test case for create_program_job

        Create Program Job
        """
        pass

    def test_get_program_release(self) -> None:
        """Test case for get_program_release

        Get Program Release
        """
        pass


if __name__ == '__main__':
    unittest.main()
