# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.8.0.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.page_job import PageJob

class TestPageJob(unittest.TestCase):
    """PageJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageJob:
        """Test PageJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageJob`
        """
        model = PageJob()
        if include_optional:
            return PageJob(
                items = [
                    {created_at=2021-01-22T23:59:52.322176, id=f622946d-fd29-35b9-a193-abdd1095167c, inputs_checksum=12345, name=solvers/isolve/releases/1.3.4/jobs/f622946d-fd29-35b9-a193-abdd1095167c, outputs_url=https://api.osparc.io/v0/solvers/isolve/releases/1.3.4/jobs/f622946d-fd29-35b9-a193-abdd1095167c/outputs, runner_name=solvers/isolve/releases/1.3.4, runner_url=https://api.osparc.io/v0/solvers/isolve/releases/1.3.4, url=https://api.osparc.io/v0/solvers/isolve/releases/1.3.4/jobs/f622946d-fd29-35b9-a193-abdd1095167c}
                    ],
                total = 0,
                limit = 1,
                offset = 0,
                links = osparc_client.models.links.Links(
                    first = '', 
                    last = '', 
                    self = '', 
                    next = '', 
                    prev = '', )
            )
        else:
            return PageJob(
                items = [
                    {created_at=2021-01-22T23:59:52.322176, id=f622946d-fd29-35b9-a193-abdd1095167c, inputs_checksum=12345, name=solvers/isolve/releases/1.3.4/jobs/f622946d-fd29-35b9-a193-abdd1095167c, outputs_url=https://api.osparc.io/v0/solvers/isolve/releases/1.3.4/jobs/f622946d-fd29-35b9-a193-abdd1095167c/outputs, runner_name=solvers/isolve/releases/1.3.4, runner_url=https://api.osparc.io/v0/solvers/isolve/releases/1.3.4, url=https://api.osparc.io/v0/solvers/isolve/releases/1.3.4/jobs/f622946d-fd29-35b9-a193-abdd1095167c}
                    ],
                total = 0,
                limit = 1,
                offset = 0,
                links = osparc_client.models.links.Links(
                    first = '', 
                    last = '', 
                    self = '', 
                    next = '', 
                    prev = '', ),
        )
        """

    def testPageJob(self):
        """Test PageJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
