# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.7.1.post0.dev0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from osparc_client.models.body_abort_multipart_upload_v0_files_file_id_abort_post import BodyAbortMultipartUploadV0FilesFileIdAbortPost

class TestBodyAbortMultipartUploadV0FilesFileIdAbortPost(unittest.TestCase):
    """BodyAbortMultipartUploadV0FilesFileIdAbortPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyAbortMultipartUploadV0FilesFileIdAbortPost:
        """Test BodyAbortMultipartUploadV0FilesFileIdAbortPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyAbortMultipartUploadV0FilesFileIdAbortPost`
        """
        model = BodyAbortMultipartUploadV0FilesFileIdAbortPost()
        if include_optional:
            return BodyAbortMultipartUploadV0FilesFileIdAbortPost(
                client_file = None
            )
        else:
            return BodyAbortMultipartUploadV0FilesFileIdAbortPost(
                client_file = None,
        )
        """

    def testBodyAbortMultipartUploadV0FilesFileIdAbortPost(self):
        """Test BodyAbortMultipartUploadV0FilesFileIdAbortPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
