name: Build and check image

on:
  # Run the workflow for pushes to the main branch
  push:
    branches:
      - main

  # Run the workflow for pull requests (from forks or within the repo)
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  node-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'node' # Here the path to the folder where package-lock.json is located.
    strategy:
      matrix:
        node-version: [24.x] # Are you are missing this specification?
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
  verify-image-build:
    needs: node-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: ooil version
        uses: docker://itisfoundation/ci-service-integration-library:v2.1.23
        with:
          args: ooil --version
      - name: escape $${ in *.y*ml files configuration
        uses: docker://itisfoundation/ci-service-integration-library:v2.1.23
        with:
          args: ooil legacy-escape
      - name: Assemble docker compose spec
        uses: docker://itisfoundation/ci-service-integration-library:v2.1.23
        with:
          args: ooil compose
      - name: Build all images if multiple
        uses: docker://itisfoundation/ci-service-integration-library:v2.1.23
        with:
          args: docker compose build